### ISSUE TITLE
No output console shows up!

### ISSUE THREAD

**Issue by abhiklodh** [lapfelix/ForceTouchVibrationCLI#1]
After running the code...as soon as I touch the trackpad, it vibrates as long as I keep my finger on it. No console window is popping up so I am not able to test out any of the commands.

**Comment by lapfelix** [comment]
<img width="531" alt="image" src="https://github.com/lapfelix/ForceTouchVibrationCLI/assets/4634735/fb099f0b-5e35-4b95-b8db-0b9a489eac67">

So you probably just ran `vibrate` with no parameters.
