### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by CodeDiseaseDev** [lapfelix/ForceTouchVibrationCLI#3]
<img width="251" alt="Screen Shot 2021-08-05 at 7 01 23 pm" src="https://user-images.githubusercontent.com/70626250/128323068-b3e86906-eb93-4f6f-8dbc-c736d7d93838.png">
I'm probably just dumb but that is the error I get when I try to build the project.

**Comment by ed6767** [comment]
this is nothing to do with this project but your development environment - solve the issues listed by XCode. you don't need to build as there is a release listed.
